export const FETCH_CITIES_BY_LAT_LNG = 'FETCH_CITIES_BY_LAT_LNG';
export const SET_INITIAL_CITY = 'SET_INITIAL_CITY';
export const SET_MARKER = 'SET_MARKER';
export const FETCH_CITY_BY_NAME = 'FETCH_CITY_BY_NAME';
export const FETCH_INITIAL_CITY = 'FETCH_INITIAL_CITY';